// Liste des devoirs, colles à venir (avec édition des chapitres) et mes
// chapitres en répétition espacée. Les tâches auto-générées (préparation de
// colle, révision espacée) ne s'affichent pas dans la liste "devoirs" brute
// — elles se gèrent depuis leurs sections dédiées ci-dessous.

import {
  getState,
  deleteTask,
  deleteOneOffEvent,
  setColleChapters,
  setDsDailyRevision,
  addChapter,
  archiveChapter,
} from '../store.js';
import { TASK_TYPE_LABELS } from '../models.js';
import { formatDateFR, formatDuration, todayISO, addDaysISO, weekdayOfISO } from '../utils/date.js';
import { minutesWorkedBetween } from '../stats.js';
import { effectiveDeadlineTime } from '../scheduler.js';

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str ?? '';
  return div.innerHTML;
}

function subjectMeta(subjectId, settings) {
  return (settings.subjects || []).find((s) => s.id === subjectId) || { label: subjectId, color: '#6B7280' };
}

// Statut affiché, dérivé des sessions plutôt que du champ `task.status`
// (réservé à une fermeture manuelle) : à faire / en cours / terminé.
function computeStatus(task, sessions) {
  const taskSessions = sessions.filter((s) => s.taskId === task.id);
  const doneMinutes = taskSessions.filter((s) => s.status === 'terminee').reduce((sum, s) => sum + s.durationMinutes, 0);
  const remaining = Math.max(0, task.estimatedDurationMinutes - doneMinutes);
  if (task.status === 'termine' || remaining <= 0) return { label: 'Terminé', remaining: 0 };
  if (doneMinutes > 0) return { label: 'En cours', remaining };
  return { label: 'À faire', remaining };
}

// Échéance affichée : l'heure saisie, sinon l'heure réellement utilisée par le
// planificateur (ex. "avant 10:00" = début du cours concerné) pour qu'on voie
// pourquoi un devoir "pour demain" n'est pas planifié le soir même.
function deadlineLabel(task, state) {
  if (task.deadlineTime) return task.deadlineTime;
  const effective = effectiveDeadlineTime(task, state.weeklyConstraints, state.oneOffEvents, state.settings);
  return effective === state.settings.dayEndCutoff ? '' : `(avant ${effective})`;
}

// Un devoir "manuel" seulement : les tâches auto-générées se gèrent depuis
// les sections Colles / Chapitres, pas depuis cette liste brute.
function isAutoGenerated(task) {
  return Boolean(task.linkedEventId || task.chapterId);
}

export function renderTaskListView(container) {
  const state = getState();
  const wrapper = document.createElement('div');
  wrapper.className = 'view view-task-list';

  wrapper.appendChild(renderTasksSection(state));
  wrapper.appendChild(renderCollesSection(state, () => rerender(container)));
  wrapper.appendChild(renderDsSection(state, () => rerender(container)));
  wrapper.appendChild(renderChaptersSection(state));

  container.appendChild(wrapper);
}

function rerender(container) {
  container.innerHTML = '';
  renderTaskListView(container);
}

// ---------------------------------------------------------------------------
// Devoirs
// ---------------------------------------------------------------------------

function renderTasksSection(state) {
  const section = document.createElement('div');
  section.className = 'section';
  section.innerHTML = '<h2>Mes devoirs</h2>';

  const todayIso = todayISO(new Date());
  const mondayOffset = (weekdayOfISO(todayIso) + 6) % 7; // 0 pour lundi, ..., 6 pour dimanche
  const weekStart = addDaysISO(todayIso, -mondayOffset);
  const weekEnd = addDaysISO(weekStart, 6);
  const weekMinutes = minutesWorkedBetween(state, weekStart, weekEnd);
  if (weekMinutes > 0) {
    const weekStat = document.createElement('p');
    weekStat.className = 'notice';
    weekStat.textContent = `Cette semaine : ${formatDuration(weekMinutes)} travaillées.`;
    section.appendChild(weekStat);
  }

  const tasks = state.tasks
    .filter((t) => !isAutoGenerated(t))
    .sort((a, b) => {
      const da = a.deadlineDate || '9999-99-99';
      const db = b.deadlineDate || '9999-99-99';
      return da < db ? -1 : da > db ? 1 : 0;
    });

  if (tasks.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'empty-state';
    empty.textContent = "Aucun devoir pour l'instant.";
    section.appendChild(empty);
  }

  tasks.forEach((task, i) => {
    const { label: statusLabel, remaining } = computeStatus(task, state.sessions);
    const subj = subjectMeta(task.subject, state.settings);

    const item = document.createElement('div');
    item.className = 'list-item task-item';
    item.style.borderLeft = `4px solid ${subj.color}`;
    item.style.setProperty('--stagger', i);
    if (statusLabel === 'Terminé') item.classList.add('is-done');

    const info = document.createElement('div');
    info.innerHTML = `
      <div>
        <span class="subject-pill" style="background:${subj.color}">${escapeHtml(subj.label)}</span>
        <strong>${escapeHtml(task.title)}</strong>
      </div>
      <div class="meta">
        ${escapeHtml(TASK_TYPE_LABELS[task.type] || task.type)} ·
        échéance ${task.deadlineDate ? formatDateFR(task.deadlineDate) : '—'} ${deadlineLabel(task, state)} ·
        ${statusLabel}${remaining > 0 ? ` (reste ${formatDuration(remaining)})` : ''}
      </div>
    `;

    const actions = document.createElement('div');
    actions.className = 'actions';

    const editBtn = document.createElement('button');
    editBtn.className = 'btn-undo';
    editBtn.textContent = '✎';
    editBtn.title = 'Modifier ce devoir';
    editBtn.addEventListener('click', () => {
      location.hash = '#/ajouter?edit=' + task.id;
    });

    const delBtn = document.createElement('button');
    delBtn.textContent = '✕';
    delBtn.title = 'Supprimer ce devoir';
    delBtn.addEventListener('click', () => {
      if (confirm(`Supprimer « ${task.title} » et toutes ses sessions planifiées ?`)) {
        deleteTask(task.id);
      }
    });

    actions.append(editBtn, delBtn);
    item.append(info, actions);
    section.appendChild(item);
  });

  return section;
}

// ---------------------------------------------------------------------------
// Colles à venir
// ---------------------------------------------------------------------------

// DS à venir : un bouton par DS pour garder ou couper sa révision quotidienne
// (les séances elles-mêmes apparaissent dans les vues Jour / Semaine).
function renderDsSection(state, onChange) {
  const section = document.createElement('div');
  section.className = 'section';
  section.innerHTML = '<h2>DS à venir</h2>';

  const nowTime = Date.now();
  const cfg = state.settings.dsDailyRevision || {};
  const upcoming = state.oneOffEvents
    .filter((e) => e.category === 'ds' && new Date(e.date + 'T' + e.endTime).getTime() > nowTime)
    .sort((a, b) => (a.date < b.date ? -1 : 1));

  if (upcoming.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'empty-state';
    empty.textContent = "Aucun DS à venir — importe le planning dans Réglages, ou ajoute-en un.";
    section.appendChild(empty);
    return section;
  }

  upcoming.slice(0, 8).forEach((event, i) => {
    const subj = subjectMeta(event.subject, state.settings);
    const on = cfg.enabled !== false && !event.skipDailyRevision;
    const task = event.linkedTaskId ? state.tasks.find((t) => t.id === event.linkedTaskId) : null;
    const item = document.createElement('div');
    item.className = 'list-item colle-item';
    item.style.borderLeft = `4px solid ${subj.color}`;
    item.style.setProperty('--stagger', i);
    item.innerHTML = `
      <div>
        <div><strong>${escapeHtml(event.label)}</strong></div>
        <div class="meta">
          ${formatDateFR(event.date)} · ${event.startTime}–${event.endTime} ·
          ${on && task ? `révision ${formatDuration(task.dailyMinutes)} par jour, ${Math.round(task.estimatedDurationMinutes / task.dailyMinutes)} jours avant` : 'pas de révision quotidienne'}
        </div>
      </div>
    `;
    const btn = document.createElement('button');
    btn.className = 'btn-undo';
    btn.textContent = on ? '✓' : '✗';
    btn.style.color = on ? '#10B981' : '';
    btn.title = on ? 'Désactiver la révision quotidienne de ce DS' : 'Activer la révision quotidienne de ce DS';
    btn.addEventListener('click', () => {
      setDsDailyRevision(event.id, !on);
      onChange();
    });
    item.appendChild(btn);
    section.appendChild(item);
  });
  if (upcoming.length > 8) {
    const more = document.createElement('p');
    more.className = 'empty-state';
    more.textContent = `… et ${upcoming.length - 8} autres DS (liste complète dans Réglages).`;
    section.appendChild(more);
  }
  return section;
}

function renderCollesSection(state, onChange) {
  const section = document.createElement('div');
  section.className = 'section';
  section.innerHTML = '<h2>Colles à venir</h2>';

  const todayIso = todayISO(new Date());
  const colles = state.oneOffEvents
    .filter((e) => e.category === 'colle' && e.date >= todayIso)
    .sort((a, b) => (a.date + a.startTime < b.date + b.startTime ? -1 : 1));

  if (colles.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'empty-state';
    empty.textContent = "Aucune colle à venir — ajoute-en une depuis l'onglet Ajouter.";
    section.appendChild(empty);
  }

  colles.forEach((event, i) => {
    const subj = subjectMeta(event.subject, state.settings);
    const chapterTitles = (event.chapterIds || [])
      .map((id) => state.chapters.find((c) => c.id === id)?.title)
      .filter(Boolean);

    const item = document.createElement('div');
    item.className = 'list-item colle-item';
    item.style.borderLeft = `4px solid ${subj.color}`;
    item.style.setProperty('--stagger', i);
    item.innerHTML = `
      <div>
        <div>
          <span class="subject-pill" style="background:${subj.color}">${escapeHtml(subj.label)}</span>
          <strong>${escapeHtml(event.label)}</strong>
        </div>
        <div class="meta">
          ${formatDateFR(event.date)} · ${event.startTime}–${event.endTime} ·
          ${chapterTitles.length ? escapeHtml(chapterTitles.join(', ')) : 'aucun chapitre choisi — rien n\'est planifié tant que tu n\'en choisis pas (✎)'}
        </div>
      </div>
    `;

    const actions = document.createElement('div');
    actions.className = 'actions';

    const editBtn = document.createElement('button');
    editBtn.className = 'btn-undo';
    editBtn.textContent = '✎';
    editBtn.title = 'Modifier les chapitres';
    editBtn.addEventListener('click', () => {
      openChapterPicker(section, event, state, onChange);
    });

    const delBtn = document.createElement('button');
    delBtn.textContent = '✕';
    delBtn.title = 'Supprimer cette colle';
    delBtn.addEventListener('click', () => {
      if (confirm(`Supprimer « ${event.label} » ?`)) {
        deleteOneOffEvent(event.id);
        onChange();
      }
    });

    actions.append(editBtn, delBtn);
    item.appendChild(actions);
    section.appendChild(item);
  });

  return section;
}

function openChapterPicker(section, event, state, onChange) {
  const existing = section.querySelector('.chapter-picker');
  if (existing) existing.remove();

  const chapters = state.chapters.filter((c) => c.subject === event.subject && c.status !== 'archive');
  const picker = document.createElement('form');
  picker.className = 'chapter-picker constraint-form';
  picker.innerHTML =
    (chapters.length
      ? '<div class="days-picker">' +
        chapters
          .map(
            (c) =>
              `<label><input type="checkbox" name="chapterId" value="${c.id}" ${
                event.chapterIds?.includes(c.id) ? 'checked' : ''
              } />${escapeHtml(c.title)}</label>`
          )
          .join('') +
        '</div>'
      : '<p class="notice">Aucun chapitre existant pour cette matière.</p>') +
    `
    <label>+ Nouveau chapitre
      <input type="text" name="newChapterTitle" placeholder="ex. Oxydoréduction" />
    </label>
    <button type="submit" class="btn-secondary">Enregistrer les chapitres</button>
  `;

  picker.addEventListener('submit', (e) => {
    e.preventDefault();
    const chapterIds = [...picker.querySelectorAll('input[name="chapterId"]:checked')].map((el) => el.value);
    const newTitle = picker.elements.newChapterTitle.value.trim();
    if (newTitle) {
      const chapter = addChapter({ subject: event.subject, title: newTitle, dateSeen: todayISO(new Date()) });
      chapterIds.push(chapter.id);
    }
    setColleChapters(event.id, chapterIds);
    onChange();
  });

  section.appendChild(picker);
}

// ---------------------------------------------------------------------------
// Mes chapitres
// ---------------------------------------------------------------------------

function stageLabel(chapter, settings) {
  const intervals = settings.spacedRepetition.baseIntervalsDays;
  if (chapter.status === 'maitrise') return 'Maîtrisé';
  if (chapter.fusedIntoEventId) return 'Fusionné avec une colle à venir';
  const days = intervals[chapter.stage];
  return days != null ? `J+${days}` : '—';
}

function renderChaptersSection(state) {
  const section = document.createElement('div');
  section.className = 'section';
  section.innerHTML = '<h2>Mes chapitres</h2>';

  const chapters = state.chapters.filter((c) => c.status !== 'archive');
  if (chapters.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'empty-state';
    empty.textContent = "Aucun chapitre pour l'instant.";
    section.appendChild(empty);
    return section;
  }

  const bySubject = new Map();
  for (const c of chapters) {
    if (!bySubject.has(c.subject)) bySubject.set(c.subject, []);
    bySubject.get(c.subject).push(c);
  }

  let chapterStagger = 0;
  for (const [subjectId, list] of bySubject) {
    const subj = subjectMeta(subjectId, state.settings);
    const subjHeading = document.createElement('div');
    subjHeading.innerHTML = `<span class="subject-pill" style="background:${subj.color}">${escapeHtml(subj.label)}</span>`;
    subjHeading.style.margin = '4px 0';
    section.appendChild(subjHeading);

    for (const chapter of list.sort((a, b) => (a.nextReviewDate || '') < (b.nextReviewDate || '') ? -1 : 1)) {
      const item = document.createElement('div');
      item.className = 'list-item';
      item.style.borderLeft = `4px solid ${subj.color}`;
      item.style.setProperty('--stagger', chapterStagger++);
      const nextInfo = chapter.status === 'maitrise' || chapter.fusedIntoEventId
        ? stageLabel(chapter, state.settings)
        : `${stageLabel(chapter, state.settings)} · prochaine révision ${chapter.nextReviewDate ? formatDateFR(chapter.nextReviewDate) : '—'}`;
      item.innerHTML = `
        <div>
          <strong>${escapeHtml(chapter.title)}</strong>
          <div class="meta">${nextInfo}</div>
        </div>
      `;
      const archiveBtn = document.createElement('button');
      archiveBtn.textContent = '✕';
      archiveBtn.title = 'Arrêter le suivi de ce chapitre';
      archiveBtn.addEventListener('click', () => {
        if (confirm(`Arrêter la répétition espacée pour « ${chapter.title} » ?`)) {
          archiveChapter(chapter.id);
        }
      });
      item.appendChild(archiveBtn);
      section.appendChild(item);
    }
  }

  return section;
}
